- platform: broadlink
  host: 192.168.8.101
  mac: "34:EA:34:E8:29:DD"
  type: "rm_mini"
  switches:
    tv:
      friendly_name: "Tele Living"
      command_on: "JgCMAJWUEDoTNhI4ERIVEhMSExISExE4FDYUNhMSERQTEhMSEBUUERM3ExISEhITExIQFRQREzcTEhU1EzcUNRE5EjgSOFUABcSXkhM3EjgRORMSEhMRFBAUExISOBQ2EjgSExMSExIQFRITDxUTNRMUFRASExAVEhMTEhA6ERQQORI4EzcTNxY0FDYXAA0FAAAAAAAAAAAAAAAA"
      command_off: "JgCMAJWUEDoTNhI4ERIVEhMSExISExE4FDYUNhMSERQTEhMSEBUUERM3ExISEhITExIQFRQREzcTEhU1EzcUNRE5EjgSOFUABcSXkhM3EjgRORMSEhMRFBAUExISOBQ2EjgSExMSExIQFRITDxUTNRMUFRASExAVEhMTEhA6ERQQORI4EzcTNxY0FDYXAA0FAAAAAAAAAAAAAAAA"
