- platform: broadlink
  host: 192.168.8.101
  mac: "34:EA:34:E8:29:DD"
  type: "rm_mini"
  switches:
    tv:
      friendly_name: "Tele Living"
      command_on: "JgBGAJWPFTMTNRQ0FA8UDxQPEhESERI2EjYTNRQPFA8UDxUOFQ8SNRQPFA8UNBQ0EhESERI2ExAUNBUzFQ4VDxUzFDQUDxQADQUAAA=="
      command_off: "JgDSAJaUEzYTNxI4EhISEhMSERMRExI4EjgSNxMSEBQSEhITEBQRExITERMRNhU3EhMQFBI3EzcSOBM2EhMRExI3EjgSEhIABgCUlBI4EzYUNhITERMSEhITEBQSNxM3EjgTERISEhMRExISERQRExISEjgSOBMRERMRORI3EzcTNxETERMRORI3ExISAAYAlJQTNhI4EzYUERISEhMRExISEjgSNxM3EhISExETEhITEhETEhMRExI3EjgTERITETgSOBI3EzcSEhITETgTNxISEgANBQAAAAAAAA=="
